### ISSUE TITLE
GT3 cars series issue

### ISSUE THREAD

**Issue by AngelFernandezSobrino** [amgart/iracingPlanner#73] opened 2023-03-15 20:11 UTC
When any of the GT3 cars are selected in the Cars tab, if the owned cars-only filter is activated the GT3 series does not show.

![image](https://user-images.githubusercontent.com/71658542/225426288-9cd54957-baa2-499d-a4fb-0cd2f2fb1116.png)

![image](https://user-images.githubusercontent.com/71658542/225426388-dc8d9bd8-0e22-4e53-bf25-a49bb1f560d1.png)

**Comment by amgart** [comment] 2023-03-16 09:23
Hi @AngelFernandezSobrino !
Thanks for using the app and taking the time to create this issue. It is easily reproducible with the Porsche 911 GT3 R.
I think the issue is the id of the car is not the same contained in the series. That is why the series is not painted green and, then not shown when filtering.
Let me investigate it deeply and I will fix this as soon as possible! 
Thanks again! :)

**Comment by amgart** [comment] 2023-06-13 04:43
Hi @AngelFernandezSobrino !
This issue should already be fixed in the latest release (2023 season 3 - v2.3.0).
If you can confirm this we can close the issue. Thanks for your help and, again, thanks for using the app! :)

**Comment by AngelFernandezSobrino** [comment] 2023-06-13 06:37
Hi! Hola! It works fine now. Thanks to you for developing the app.

Also (just an opinion), maybe would be better to remove the header toolbar in app.component.html, so it looks more native. I would also remove the margins (which are default css for chromium as I can check on the devtools, just setting it to 0 from the body). Again, it is just a UI design opinion, the app is really good and performs nicely). You can close the issue! Thanks again.

**Comment by amgart** [comment] 2023-06-13 07:48
Hi @AngelFernandezSobrino !
I have some styling improvements in my mind also but for sure I will take into account your opinion.
Thanks! :)

**Closed by amgart** 2023-06-13 07:48 UTC
